#version 460
#extension GL_GOOGLE_include_directive : require

#include "src/gfx/spirv/atmosphere_common.glsl"

layout(set = 0, binding = 1) uniform sampler2D transmittance_texture;
layout(set = 0, binding = 2, rgba16f) uniform writeonly image2D
    delta_irradiance_output;
layout(set = 0, binding = 3, rgba16f) uniform writeonly image2D
    irradiance_output;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main() {
  const ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
  if (any(greaterThanEqual(
          pixel, ivec2(IRRADIANCE_TEXTURE_WIDTH,
                       IRRADIANCE_TEXTURE_HEIGHT)))) {
    return;
  }
  const vec3 direct = ComputeDirectIrradianceTexture(
      ATMOSPHERE, transmittance_texture, vec2(pixel) + vec2(0.5));
  imageStore(delta_irradiance_output, pixel, vec4(direct, 1.0));
  imageStore(irradiance_output, pixel, vec4(0.0, 0.0, 0.0, 1.0));
}
