#!/usr/bin/env python3
"""Regenerate src/app/ui_glyph_ranges.inc from UI source strings."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "app" / "ui_glyph_ranges.inc"

# Names / credits that must render even if not in other UI strings
EXPLICIT = """
卡门线 黑体 微软雅黑
"""

SKIP_PARTS = {"third_party", "build", "build-app", "vcpkg_installed", "tools", ".git",
              "vcpkg_installed", "glslang"}


def add_chars(codes: set[int], text: str) -> None:
    for ch in text:
        o = ord(ch)
        if (
            0x00A0 <= o <= 0x024F
            or 0x2000 <= o <= 0x206F
            or 0x3000 <= o <= 0x303F
            or 0x4E00 <= o <= 0x9FFF
            or 0xFF00 <= o <= 0xFFEF
        ):
            codes.add(o)


def harvest_sources() -> set[int]:
    codes: set[int] = set()
    add_chars(codes, EXPLICIT)
    # i18n JSON catalogs (runtime UI strings)
    i18n_dir = ROOT / "i18n"
    if i18n_dir.is_dir():
        for path in i18n_dir.glob("*.json"):
            try:
                add_chars(codes, path.read_text(encoding="utf-8"))
            except OSError:
                pass
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix.lower() not in {".cpp", ".hpp", ".h", ".inc", ".txt", ".json", ".md"}:
            continue
        if any(p in SKIP_PARTS for p in path.parts):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        add_chars(codes, text)
    # Always include these punctuation marks
    for o in (
        0x00B0,
        0x00D7,
        0x2013,
        0x2014,
        0x2026,
        0x2192,
        0x3001,
        0x3002,
        0xFF08,
        0xFF09,
        0xFF0C,
        0xFF1A,
    ):
        codes.add(o)
    return codes


def to_runs(codes: list[int]) -> list[tuple[int, int]]:
    if not codes:
        return []
    runs: list[tuple[int, int]] = []
    start = end = codes[0]
    for c in codes[1:]:
        if c == end + 1:
            end = c
        else:
            runs.append((start, end))
            start = end = c
    runs.append((start, end))
    return runs


def main() -> None:
    codes = sorted(harvest_sources())
    runs = to_runs(codes)
    lines = [
        "// Auto-generated by tools/gen_ui_glyphs.py — do not edit by hand.",
        "// Covers every non-Latin character referenced by the desktop UI.",
        "static const nk_rune kUiGlyphRanges[] = {",
        "    0x0020, 0x00FF,  // Basic Latin + Latin-1",
    ]
    for a, b in runs:
        lines.append(f"    0x{a:04X}, 0x{b:04X},")
    lines.append("    0")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Sanity: critical toolbar labels
    critical = [
        "打开模型",
        "导入贴图",
        "显示骨骼",
        "烘焙",
        "空闲",
        "清除贴图",
        "导出速度",
        "全局物理参数",
        "简单（片尾→目标开头）",
        "卡门线",
    ]
    code_set = set(codes)
    for s in critical:
        miss = [ch for ch in s if ord(ch) >= 0x80 and ord(ch) not in code_set]
        status = "OK" if not miss else "MISS " + "".join(miss)
        print(f"{s}: {status}")
    print(f"Wrote {OUT} ({len(codes)} codepoints, {len(runs)} runs)")


if __name__ == "__main__":
    main()
